name: Deploy docs

on: 
  push:
    branches:
      - main

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: npm ci
          build_command: npm run build
          path: storybook-static
          checkout: true

      # - run: npm ci

      # - run: npm run build

      # - name: Deploy storybook
      #   working-directory: ./packages/docs
      #   run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
      #   env:
      #     GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}